Fix for automute Translation of remaining comments into English Editing the web interface design Changing player priorities

diff --git a/ext_tree/board/luckfox/rootfs_overlay/etc/rc.pure/S95apscream b/ext_tree/board/luckfox/rootfs_overlay/etc/rc.pure/S95apscream
--- a/ext_tree/board/luckfox/rootfs_overlay/etc/rc.pure/S95apscream
+++ b/ext_tree/board/luckfox/rootfs_overlay/etc/rc.pure/S95apscream
@@ -4,7 +4,15 @@ start() {
     touch /var/log/apscream.log
     ln -s -f /var/log/apscream.log /usr/apscream/apscream.log
     printf "Starting APscream: "
-    cd /usr/apscream; nice -n -30 ./apscream > /dev/null 2>&1 && echo "OK" || echo "FAIL"
+    cd /usr/apscream; ./apscream > /dev/null 2>&1 && echo "OK" || echo "FAIL"
+    sleep 0.5
+    pid=$(pidof apscream)
+    if [ -n "$pid" ]; then
+    renice -15 $pid
+    for tid in $(ls /proc/$pid/task/); do
+        renice -15 $tid
+    done
+    fi
     sync
     MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
     /usr/bin/amixer set "$MIXER" unmute
diff --git a/ext_tree/board/luckfox/rootfs_overlay/etc/rc.pure/S95apsq b/ext_tree/board/luckfox/rootfs_overlay/etc/rc.pure/S95apsq
--- a/ext_tree/board/luckfox/rootfs_overlay/etc/rc.pure/S95apsq
+++ b/ext_tree/board/luckfox/rootfs_overlay/etc/rc.pure/S95apsq
@@ -5,7 +5,15 @@ start() {
     ln -s -f /var/log/aprenderer.log /usr/aprenderer/aprenderer.log
     printf "Starting APlayer UPNP: "
     /usr/aprenderer/upnp/squeeze2upnp -z -k -I > /dev/null 2>&1
-    cd /usr/aprenderer; nice -n -30 ./aprenderer > /dev/null 2>&1 && echo "OK" || echo "FAIL"
+    cd /usr/aprenderer; ./aprenderer > /dev/null 2>&1 && echo "OK" || echo "FAIL"
+    sleep 0.5
+    pid=$(pidof aprenderer)
+    if [ -n "$pid" ]; then
+    renice -15 $pid
+    for tid in $(ls /proc/$pid/task/); do
+        renice -15 $tid
+    done
+    fi
     sync
     MIXER=`amixer 2>/dev/null| awk -F "'" 'NR==1 {print $2; exit}'`
     /usr/bin/amixer set "$MIXER" unmute
